blank_issues_enabled: true
contact_links:
  - name: Usage questions
    url: https://github.com/felixdittrich92/docTR-Synth-Generator/discussions
    about: Ask questions and discuss with other docTR-Synth-Generator community members